export const funnyExcuses = [
    "I'm emotionally attached to this repository.",
    "This README finally looks good.",
    "I spent three hours fixing one CSS bug.",
    "The commit history has feelings.",
    "My AI assistant said no.",
    "I promised GitHub I wouldn't.",
    "Deleting this reduces my caffeine ROI.",
    "The bugs have become family.",
    "I finally centered the div.",
    "Future recruiters deserve to see this.",
    "I haven't even pushed this to production yet.",
    "My keyboard died for this code.",
    "It works on my machine, so it stays.",
    "Git would be very disappointed.",
    "Stack Overflow wouldn't want this.",
    "I'm keeping this for the aesthetic.",
    "The 10x engineer in me says keep it.",
    "It compiles without warnings. Rare.",
    "I wrote this at 3 AM. It's a masterpiece.",
    "This code is holding the site together.",
    "Deleting this causes a paradox.",
    "I lost the backup, so this is all I have.",
    "The dark mode colors are too perfect here.",
    "I need this for my imposter syndrome.",
    "Vercel would be sad."
];
